export const STATUS_OPTIONS = [
  { value: 'new', label: 'New' },
  { value: 'contacted', label: 'Contacted' },
  { value: 'responded', label: 'Responded' },
  { value: 'won', label: 'Won' },
  { value: 'not_interested', label: 'Not Interested' },
] as const;

export const CATEGORY_OPTIONS = [
  { value: '', label: 'All Categories' },
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'cafe', label: 'Cafe' },
  { value: 'bar', label: 'Bar' },
  { value: 'bakery', label: 'Bakery' },
  { value: 'beauty_salon', label: 'Beauty Salon' },
  { value: 'hair_care', label: 'Hair Care' },
  { value: 'spa', label: 'Spa' },
  { value: 'gym', label: 'Gym' },
  { value: 'dentist', label: 'Dentist' },
  { value: 'doctor', label: 'Doctor' },
  { value: 'lawyer', label: 'Lawyer' },
  { value: 'accounting', label: 'Accounting' },
  { value: 'real_estate_agency', label: 'Real Estate' },
  { value: 'car_repair', label: 'Car Repair' },
  { value: 'car_wash', label: 'Car Wash' },
  { value: 'pet_store', label: 'Pet Store' },
  { value: 'florist', label: 'Florist' },
  { value: 'clothing_store', label: 'Clothing Store' },
  { value: 'hardware_store', label: 'Hardware Store' },
  { value: 'pharmacy', label: 'Pharmacy' },
  { value: 'supermarket', label: 'Supermarket' },
  { value: 'laundry', label: 'Laundry' },
  { value: 'locksmith', label: 'Locksmith' },
  { value: 'electrician', label: 'Electrician' },
  { value: 'plumber', label: 'Plumber' },
  { value: 'painter', label: 'Painter' },
  { value: 'roofing_contractor', label: 'Roofing' },
  { value: 'moving_company', label: 'Moving Company' },
  { value: 'storage', label: 'Storage' },
  { value: 'travel_agency', label: 'Travel Agency' },
  { value: 'insurance_agency', label: 'Insurance Agency' },
] as const;

export const DEFAULT_SCAN_CONFIG = {
  location: '',
  radius_km: 5,
  min_rating: 3.0,
  max_rating: 4.5,
  category: '',
};
